use mydb;
show tables;
SELECT * FROM EMP;
SELECT * FROM EMP LIMIT 5;
SELECT * FROM EMP;
SELECT * FROM EMP ORDER BY SALARY;
SELECT * FROM EMP ORDER BY SALARY DESC;
SELECT * FROM EMP ORDER BY SALARY;
SELECT * FROM EMP ORDER BY ENAME DESC;
SELECT * FROM EMP ORDER BY DEPT;
SELECT * FROM EMP ORDER BY DEPT, SALARY;#HIERARCHIAL ORDERING
SELECT EMPID,ENAME,DEPT FROM EMP;#PROJECTIONS
SELECT * FROM EMP;
SELECT SALARY,ENAME AS EMP_NAME,DEPT AS DEPARTMENT FROM EMP; #COLUMN OUTPUT ALLIANCE